sudo: false

language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '9'

before_script:
  - npm prune

script:
  - npm run build
  - cd public
  - npm i -g now-pipeline@1.10.0
  - DEBUG=now-pipeline

  # - now-pipeline-list
  # - now-pipeline --alias scottspence.now.sh

after_success:
  # - ls -la
