sudo: false

language: node_js

notifications:
  email: false

node_js:
  - '9'

before_script:
  - npm prune

script:
  - npm run build
  - npm i -g now-pipeline
  - now-pipeline --dir /public

  - now-pipeline-list
  - now-pipeline --alias scottspence.now.sh

