sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune
script:
  - npm run clean
  - npm run format
  - npm run build
  - npm install -g now-pipeline@1.7.1
  - now-pipeline-prune
  - DEBUG=now-pipeline now-pipeline --test "npm run prod-test"
