sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune
script:
  - npm run clean
  - npm run format
  - npm run build
  - npm i -g now-pipeline
  - now-pipeline-prune
  - now-pipeline "npm run deploy"
  - now-pipeline-list
  - now-pipeline --alias scottspence.now.sh