siteTitle = "Blog by Scott Spence"
siteDescr = "VBA developer learning other stuff with @freeCodeCamp(🔥) Some may call this junk... Me, I call them treasures.."
siteAuthor = "Scott Spence"

siteTelegramUrl = "#"
siteTwitterUrl = "https://twitter.com/ScottDevTweets"
siteGithubUrl = "https://github.com/spences10"
siteEmailUrl = "mailto:spences10apps@gmail.com"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = "UA-87264973-1"

linkPrefix = "/"
