backend:
  name: github
  repo: spences10/blog.scottspence.me
  branch: develop/gatsby-v2

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: posts
    create: true
    slug: '{{year}}{{month}}{{day}}-{{slug}}'
    fields:
      - { name: path, label: Path, widget: string }
      - { name: date, label: Date and Time, widget: datetime }
      - { name: title, label: Title }
      - { name: tags, label: Tags, widget: list }
      - { label: Tag, name: tag_item, widget: string }
      - { name: published, label: Published, widget: boolean }
      - { name: body, label: Body, widget: markdown }
