backend:
  name: github
  repo: spences10/blog.scottspence.me
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: posts
    create: true
    slug: '{{year}}{{month}}{{day}}-{{slug}}'
    fields:
      - { name: path, label: Path, required: true, widget: string }
      - {
          name: date,
          label: Date and Time,
          required: true,
          widget: datetime,
        }
      - { name: title, label: Title, required: true, widget: string }
      - { name: tags, label: Tags, required: true, widget: string }
      - {
          name: published,
          label: Published,
          required: true,
          widget: boolean,
          default: false,
        }
      - { name: body, label: Body, required: true, widget: markdown }
